[package]
name = "epub2txt"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = "6.0"
regex = "1.11.1"
anyhow = "1.0.95"
xml-rs = "1.0"
kuchiki = "0.8"
html-escape = "0.2.13"
serde = { version = "1.0", features = ["derive"] }
toml_edit = "0.23"